version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.django
    
    
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
      - ./logs:/app/logs # Added in logging setup
    expose:
      - "8000"
      - "9001" # Added to access supervisor logs
    ports:
      - "9001:9001"  # Map port 9001 from host to container
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./logs:/var/log/nginx # Added in logging setup
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
