# Generated by Django 5.0.3 on 2024-04-11 10:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("exchange", models.CharField(max_length=20)),
                ("exchange_short", models.CharField(max_length=20)),
                ("listing_type", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("type", models.CharField(max_length=3)),
                ("symbol", models.CharField(max_length=20)),
                ("transaction_shares", models.IntegerField()),
                ("shares_outstanding", models.IntegerField(blank=True, null=True)),
                (
                    "transaction_value_per_share",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "transaction_value_total",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("STCG", models.DecimalField(decimal_places=2, max_digits=10)),
                ("LTCG", models.DecimalField(decimal_places=2, max_digits=10)),
                ("STCG_tax", models.DecimalField(decimal_places=2, max_digits=10)),
                ("LTCG_tax", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
