# Generated by Django 5.0.3 on 2024-04-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brokerage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="exchange",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="listing",
            name="exchange_short",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="listing",
            name="listing_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="listing",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="listing",
            name="symbol",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
