# Generated by Django 5.0.3 on 2024-04-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "brokerage",
            "0003_alter_listing_exchange_alter_listing_exchange_short_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="LTCG",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="LTCG_tax",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="STCG",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="STCG_tax",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
